FROM ruby:3.3.6

ENV RAILS_ENV=development

RUN apt update -qq && \
  apt install -y --no-install-recommends build-essential libpq-dev curl && \
  curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
  apt install -y --no-install-recommends nodejs && \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg -o /root/yarn-pubkey.gpg && \
  apt-key add /root/yarn-pubkey.gpg && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list && \
  apt update && \
  apt install -y --no-install-recommends yarn && \
  apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile* ./

RUN bundle lock --add-platform ruby
RUN bundle lock --add-platform x86_64-linux
RUN gem install mini_portile2 -v 2.8.0
RUN bundle install -j $(nproc)
